// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX2JnttYZe0f0caupp_t2P-rLZB3HI_3Q',
    appId: '1:913103323990:web:23f2c4b9f5f8e58c19ccf7',
    messagingSenderId: '913103323990',
    projectId: 'study-planner-f0132',
    authDomain: 'study-planner-f0132.firebaseapp.com',
    storageBucket: 'study-planner-f0132.appspot.com',
    measurementId: 'G-V7WGV1HB5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdHMHYGXOCWziqYdgDguXz7s7BSpJpls',
    appId: '1:913103323990:android:9e1d9bf4f2c246a319ccf7',
    messagingSenderId: '913103323990',
    projectId: 'study-planner-f0132',
    storageBucket: 'study-planner-f0132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YLEidZB2dJnlVeFGYRtjkjDi0Sq7XwM',
    appId: '1:913103323990:ios:87a5cf56587253eb19ccf7',
    messagingSenderId: '913103323990',
    projectId: 'study-planner-f0132',
    storageBucket: 'study-planner-f0132.appspot.com',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_YLEidZB2dJnlVeFGYRtjkjDi0Sq7XwM',
    appId: '1:913103323990:ios:5a8431acd6e8e9ef19ccf7',
    messagingSenderId: '913103323990',
    projectId: 'study-planner-f0132',
    storageBucket: 'study-planner-f0132.appspot.com',
    iosBundleId: 'com.example.studyPlanner.RunnerTests',
  );
}
